name: segm
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - contourpy=1.3.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - expat=2.7.1
  - ffmpeg=4.3
  - filelock=3.17.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.14.0.30
  - libcups=2.4.2
  - libcurand=10.3.10.19
  - libcurl=8.12.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.0.1
  - libxml2=2.13.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - numexpr=2.10.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.2
  - pandas=1.5.3
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.1
  - pthread-stubs=0.3
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - requests=2.32.3
  - setuptools=78.1.1
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tomli=2.0.1
  - torchaudio=2.2.2
  - torchtriton=2.2.0
  - torchvision=0.17.2
  - tornado=6.4.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wheel=0.45.1
  - xcb-util-cursor=0.1.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - fsspec==2025.7.0
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - joblib==1.5.2
      - opencv-python==4.11.0.86
      - polars==1.37.1
      - polars-runtime-32==1.37.1
      - psutil==7.2.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tqdm==4.67.1
      - ultralytics==8.4.8
      - ultralytics-thop==2.0.18
prefix: /home/jackie/anaconda3/envs/segm
